FORMAT: 1A
HOST: http://thefretboard.co.uk/api/v1

# TheFretboard

This is an API for thefretboard.co.uk

## Categories [/categories/list]

### List All Categories [GET]

Get a list of all discussion categories.

This is based on the [Vanilla categories/list API](http://docs.vanillaforums.com/api/categories/)

You can see an example of the original API output by doing:

curl http://forums.xamarin.com/api/v1/categories/list.json

+ Response 200 (application/json)

        {
            # This entry represents a leaf in the category tree (ParentCategoryID = -1)
            "1": {
                "CategoryID": 1,
                "ParentCategoryID": -1,
                "ChildIDs": [101],

                "Name": "Gear"
            },
            
            # This entry represents a non-leaf node in the category tree (ParentCategoryID = -1)
            "2": {
                "CategoryID": 2,
                "ParentCategoryID": 0,
                "ChildIDs": [],

                "Name": "Playing"
            },
            
            # This entry represents a leaf in the category tree
            "101": {
                "CategoryID": 101,
                "ParentCategoryID": 1,
                "ChildIDs": [],
                
                "Name": "Guitar",

                "CountAllDiscussions": 11204,
                "CountAllComments": 489339,
                
                # Most recent discussion in this category
                "LastDiscussionID": 4793,
                "LastDiscussionUserID": 4834,
                "LastDiscussionUserName": "Joe Bloggs",
                "LastDiscussionUserImage": "http://thefretboard.co.uk/uploads/userpics/4834/j3484n.jpg",
                "LastDiscussionDate": "2016-03-04 02:48:28",
                
                # Most recent comment in this category
                "LastCommentID": 4349,
                "LastCommentUserID": 2343,
                "LastCommentUserName": "Fred Flintstone",
                "LastCommentUserImage": "http://thefretboard.co.uk/uploads/userpics/2343/dfg4322.jpg",
                "LastCommentDate": "2016-03-04 04:48:28",
            }
        }